# Generated by Django 4.2.7 on 2024-01-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'материал', 'verbose_name_plural': 'материалы'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='material',
            order_with_respect_to='section',
        ),
    ]
