# Generated by Django 4.2.7 on 2023-12-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='last_update',
            field=models.DateTimeField(blank=True, help_text='Дата обновления должна быть больше даты создания', null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='material',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='material_media', to='education.media', verbose_name='Медиа'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(help_text='Не более 100 символов', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='material',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_section', to='education.section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='media',
            name='external_audio',
            field=models.URLField(blank=True, help_text='Только одно поле может быть выбрано', null=True, verbose_name='Внешнее аудио'),
        ),
        migrations.AlterField(
            model_name='media',
            name='external_image',
            field=models.URLField(blank=True, help_text='Только одно поле может быть выбрано', null=True, verbose_name='Внешнее изображение'),
        ),
        migrations.AlterField(
            model_name='media',
            name='external_video',
            field=models.URLField(blank=True, help_text='Только одно поле может быть выбрано', null=True, verbose_name='Внешнее видео'),
        ),
        migrations.AlterField(
            model_name='media',
            name='local_audio',
            field=models.FileField(blank=True, help_text='Только одно поле может быть выбрано', null=True, upload_to='education/media/audios/%Y/%m%d/', verbose_name='Локальное аудио'),
        ),
        migrations.AlterField(
            model_name='media',
            name='local_image',
            field=models.ImageField(blank=True, help_text='Только одно поле может быть выбрано', null=True, upload_to='education/media/images/%Y/%m%d/', verbose_name='Локальное изображение'),
        ),
        migrations.AlterField(
            model_name='media',
            name='local_video',
            field=models.FileField(blank=True, help_text='Только одно поле может быть выбрано', null=True, upload_to='education/media/videos/%Y/%m%d/', verbose_name='Локальное видео'),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(help_text='Не более 100 символов', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='section',
            name='last_update',
            field=models.DateTimeField(blank=True, help_text='Дата обновления должна быть больше даты создания', null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='section',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='section_media', to='education.media', verbose_name='Медиа'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='Не более 100 символов', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='test',
            name='last_update',
            field=models.DateTimeField(blank=True, help_text='Дата обновления должна быть больше даты создания', null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='test',
            name='material',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_material', to='education.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question',
            field=models.ManyToManyField(related_name='test_question', to='education.testquestion', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='answer',
            field=models.CharField(help_text='Не более 1000 символов', max_length=1000, verbose_name='Выбор варианта ответа'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testquestion_answer', to='education.testanswer', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='choices',
            field=models.ManyToManyField(related_name='testquestion_choices', to='education.testanswer', verbose_name='Варианты ответа'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='testquestion_media', to='education.media', verbose_name='Медиа'),
        ),
    ]
