# Generated by Django 4.2.7 on 2023-12-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='external_audio',
            field=models.URLField(blank=True, null=True, verbose_name='Внешнее аудио'),
        ),
        migrations.AddField(
            model_name='media',
            name='local_audio',
            field=models.FileField(blank=True, null=True, upload_to='education/media/audios/%Y/%m%d/', verbose_name='Локальное аудио'),
        ),
    ]
