# Generated by Django 4.2.7 on 2024-01-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='material',
            table_comment='Модель материала к разделам',
        ),
        migrations.AlterModelTableComment(
            name='media',
            table_comment='Модель медиафайла для разделов, материалов, вопросов к тестам',
        ),
        migrations.AlterModelTableComment(
            name='section',
            table_comment='Модель раздела',
        ),
        migrations.AlterModelTableComment(
            name='test',
            table_comment='Модель теста к материалу',
        ),
        migrations.AlterModelTableComment(
            name='testanswer',
            table_comment='Модель ответа на вопрос теста',
        ),
        migrations.AlterModelTableComment(
            name='testquestion',
            table_comment='Модель вопроса к тесту',
        ),
    ]
