# Generated by Django 4.2.7 on 2023-12-29 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Значение от 12 до 120', null=True, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(120)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='Не указан', help_text='Не более 100 символов', max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='Не более 50 символов', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='Не более 50 символов', max_length=50, verbose_name='Фамилия'),
        ),
    ]
