# Generated by Django 4.2.7 on 2024-01-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='customuser',
            table_comment='Кастомная и основная модель пользователя',
        ),
    ]
