# Generated by Django 4.2.7 on 2023-12-17 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='/path_to_default_avatar.jpg', null=True, upload_to='users/media/avatars/', validators=[django.core.validators.validate_image_file_extension], verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='Не указан', max_length=100, null=True, verbose_name='Город'),
        ),
    ]
