# Generated by Django 4.2.7 on 2024-01-10 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('FULL', 'Полная'), ('SHARE_30D4P', 'Долями. 30 дней. 4 оплаты')], max_length=11, verbose_name='Тип оплаты')),
                ('payment_method', models.CharField(choices=[('STIPE', 'Ссылка STRIPE')], max_length=5, verbose_name='Способ оплаты')),
                ('payments_left', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во оставшихся оплат')),
                ('last_payment_date', models.DateTimeField(auto_now=True, verbose_name='Дата последней оплаты')),
                ('paid_section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='education.section', verbose_name='Раздел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплаты',
                'ordering': ('paid_section',),
            },
        ),
    ]
