# Generated by Django 4.2.7 on 2024-01-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('paid_section',), 'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_payment_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('STIPE', 'Ссылка STRIPE')], max_length=5, verbose_name='Способ платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('FULL', 'Полная'), ('SHARE_30D4P', 'Долями. 30 дней. 4 платежа')], max_length=11, verbose_name='Тип платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payments_left',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во оставшихся платежей'),
        ),
    ]
