# Generated by Django 4.2.7 on 2024-01-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
        migrations.AlterModelTableComment(
            name='payment',
            table_comment='Модель платежей за разделы',
        ),
        migrations.AlterOrderWithRespectTo(
            name='payment',
            order_with_respect_to='user',
        ),
    ]
