# Generated by Django 4.2.7 on 2024-01-16 20:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_alter_payment_options_alter_payment_table_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(16)], verbose_name='Номер карты')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Владелец')),
                ('expiration_month', models.PositiveSmallIntegerField(verbose_name='Месяц действия')),
                ('expiration_year', models.PositiveSmallIntegerField(verbose_name='Год действия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'банковская карта',
                'verbose_name_plural': 'банковские карты',
                'db_table_comment': 'Модель банковской карты пользователя',
                'ordering': ('card_number',),
            },
        ),
    ]
